name = input("Enter your name: ")
print("The user's name is : ", name)
Droids = input("Number of Droids: ")
print("Number of Droids Stored : ", Droids)
Wookiees = input("Number of Wookiees: ")
print("Number of Wookiees Stored : ", Wookiees)
print(name, "wants to meet", Droids, "Droids and", Wookiees, "Wookiees!")